### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by proviancy** [13ace37/discordjs-surftimer#17]
**Describe the bug**
Installation error when running the script

**Expected behavior**
The script would start

**Additional context**
csgoapril@hosted11 ~/public/discord $ node ./index.js
internal/modules/cjs/loader.js:896
  throw err;
  ^

Error: Cannot find module '/usr/www/csgoapril/public/discord/util/handler'
Require stack:
- /usr/www/csgoapril/public/discord/index.js

**Comment by 13ace37** [comment]
I know that. I'm not supporting this version anymore.

**Comment by proviancy** [comment]
What can I use for discord SurfTimer integration?

**Comment by 13ace37** [comment]
Either you downgrade to the version I added the multi db support or u need to wait for the first release of my recode https://github.com/13ace37/surftimer-bot
